WITH PROMOCIONES_ABANDONO AS (

    SELECT
        CAMP_PROM_ID,
        COALESCE(PAZOS_CODIGO_PROMO, VNTA_CODIGO_PROMOCION) AS VNTA_CODIGO_PROMOCION,
        GEO_PROMOTION,
        CAMP_PROM_FINI,
        CAMP_PROM_FFIN,
        CAMP_PROM_UNNG,
        CAMP_PROM_TIPO,
        CAMP_PROM_NOMBRE,
        CAMP_PROM_ESPECIFICACION,
        CAMP_PROM_OBJETIVO,
        CAMP_PROM_APLICACION,
        CAMP_PROM_CANAL
    FROM
        SANDBOX_PLUS.DWH.DETALLE_PROMO AS A
        LEFT JOIN MSTRDB.DWH.LU_PROMO_RPM AS L on L.RPM_CODIGO_PROMO = A.VNTA_CODIGO_PROMOCION
    WHERE
        CAMP_PROM_OBJETIVO <> 'Informativo'
        AND CAMP_PROM_NOMBRE ILIKE '%ABANDO%'
        AND YEAR(CAMP_PROM_FINI) >= YEAR(CURRENT_DATE) - 1
    ORDER BY
        CAMP_PROM_ID DESC

) 
,

IMPACTADOS_ABANDONO AS (

    SELECT
        YEAR(FECHA_CARGA) AS ANIO,
        MONTH(FECHA_CARGA) AS MES,
        COUNT(DISTINCT(SOCI_SOCI_ID)) AS IMPACTADOS
    FROM
        SANDBOX_PLUS.DWH.DETALLE_CLIENTES
    WHERE
        CAMP_PROM_ID IN (SELECT DISTINCT CAMP_PROM_ID FROM PROMOCIONES_ABANDONO)
    GROUP BY
        ALL
        
)
,
TICKETS_TOTAL AS (

    SELECT
        DISTINCT
        TIEM_DIA_ID,
        GEOG_LOCL_ID,
        VNTA_NRO_TICKET,
        VNTA_NRO_CAJA,
        VNTA_COD_DESCUENTO,
        TICKET,
        CAMP_PROM_ID,
        CAMP_PROM_NOMBRE,
        CAMP_PROM_ESPECIFICACION,
        CAMP_PROM_FINI,
        CAMP_PROM_FFIN,
        CAMP_PROM_UNNG,
        CAMP_PROM_CANAL,
        B.VNTA_CODIGO_PROMOCION
    FROM
        MSTRDB.DWH.FT_VENTAS_DESCUENTOS_LINEAS A
         INNER JOIN PROMOCIONES_ABANDONO B ON (
                A.VNTA_COD_DESCUENTO::VARCHAR = B.VNTA_CODIGO_PROMOCION 
                OR A.VNTA_CODIGO_PROMOCION::VARCHAR = B.VNTA_CODIGO_PROMOCION
                OR A.VNTA_CODIGO::VARCHAR = B.VNTA_CODIGO_PROMOCION
                OR A.VNTA_COD_DESCUENTO::VARCHAR = B.GEO_PROMOTION AND B.GEO_PROMOTION IS NOT NULL
                OR A.VNTA_CODIGO_PROMOCION::VARCHAR = B.GEO_PROMOTION AND B.GEO_PROMOTION IS NOT NULL
                OR A.VNTA_CODIGO::VARCHAR = B.GEO_PROMOTION AND B.GEO_PROMOTION IS NOT NULL
            ) AND A.TIEM_DIA_ID BETWEEN B.CAMP_PROM_FINI AND B.CAMP_PROM_FFIN
    WHERE
        YEAR(TIEM_DIA_ID) >= YEAR(CURRENT_DATE) - 1
        AND B.CAMP_PROM_APLICACION = 'Total'

) 
,
ACCION_ABANDONO_TOTAL AS (
    SELECT
        'TATA' AS UNIDAD_NEGOCIO,
        'ABANDONO' AS ACCION,
        'REACTIVACION CLIENTES' AS OBJETIVO,
        YEAR(FV.TIEM_DIA_ID) ANIO,
        MONTH(FV.TIEM_DIA_ID) AS MES,
        COUNT(DISTINCT(FV.TICKET)) AS TICKETS,
        ROUND(SUM(FV.VNTA_IMPORTE_SIN_IVA)) AS VTA_PROMO,
        ROUND(SUM(FV.VNTA_IMPORTE_SIN_IVA - (FV.VNTA_UNIDADES * FV.VNTA_COSTO_PROM_POND))) AS GB1_PROMO,
        ROUND(GB1_PROMO / VTA_PROMO, 2) AS MARGEN_PROMO,
        COUNT(DISTINCT(FFM.SOCI_SOCI_ID)) AS SOCIOS_CON_PROMO,
        IMPACTADOS,
        ROUND((SOCIOS_CON_PROMO / IMPACTADOS) * 100, 2) AS REDENCION
    FROM
        MSTRDB.DWH.FT_VENTAS AS FV
        INNER JOIN TICKETS_TOTAL AS TT
            ON FV.TIEM_DIA_ID = TT.TIEM_DIA_ID 
            AND FV.VNTA_NRO_TICKET = TT.VNTA_NRO_TICKET 
            AND FV.GEOG_LOCL_ID = TT.GEOG_LOCL_ID
            AND FV.VNTA_NRO_CAJA = TT.VNTA_NRO_CAJA
        INNER JOIN MSTRDB.DWH.FT_FDLN_MOVIMIENTOS AS FFM
            ON FV.TIEM_DIA_ID = FFM.TIEM_DIA_ID
            AND FV.VNTA_NRO_TICKET = FFM.VNTA_NRO_TICKET
            AND FV.GEOG_LOCL_ID = FFM.GEOG_LOCL_ID 
            AND FV.VNTA_NRO_CAJA = FFM.VNTA_NRO_CAJA
        LEFT JOIN IMPACTADOS_ABANDONO AS IA ON YEAR(FV.TIEM_DIA_ID) = IA.ANIO AND MONTH(FV.TIEM_DIA_ID) = IA.MES
    WHERE
        YEAR(FV.TIEM_DIA_ID) >= YEAR(CURRENT_DATE) - 1
        AND FFM.FDLN_MOVT_TIPO = 'RP'
        AND FV.TICKET IN (SELECT DISTINCT TICKET FROM TICKETS_TOTAL)
    GROUP BY
        ALL
ORDER BY
    1 DESC,
    2,
    3
) 
,
PROMOCIONES_FOCO_NOABANDONO AS (

    SELECT
        CAMP_PROM_ID,
        COALESCE(PAZOS_CODIGO_PROMO, VNTA_CODIGO_PROMOCION) AS VNTA_CODIGO_PROMOCION,
        GEO_PROMOTION,
        CAMP_PROM_FINI,
        CAMP_PROM_FFIN,
        CAMP_PROM_UNNG,
        CAMP_PROM_TIPO,
        CAMP_PROM_NOMBRE,
        CAMP_PROM_ESPECIFICACION,
        CAMP_PROM_OBJETIVO,
        CAMP_PROM_APLICACION,
        CAMP_PROM_CANAL
    FROM
        SANDBOX_PLUS.DWH.DETALLE_PROMO AS A
        LEFT JOIN MSTRDB.DWH.LU_PROMO_RPM AS L on L.RPM_CODIGO_PROMO = A.VNTA_CODIGO_PROMOCION
    WHERE
        CAMP_PROM_OBJETIVO <> 'Informativo'
        AND YEAR(CAMP_PROM_FINI) >= YEAR(CURRENT_DATE) - 1
        AND (CAMP_PROM_NOMBRE ILIKE '%FRECUENCIA%' OR CAMP_PROM_NOMBRE ILIKE 'LOCALES EN FOCO' OR CAMP_PROM_NOMBRE ILIKE '%ACCION CRUZA%')
    ORDER BY
        CAMP_PROM_ID DESC

)
,
IMPACTADOS_NO_ABANDONO AS (

    SELECT
        YEAR(FECHA_CARGA) AS ANIO,
        MONTH(FECHA_CARGA) AS MES,
        COUNT(DISTINCT(SOCI_SOCI_ID)) AS IMPACTADOS
    FROM
        SANDBOX_PLUS.DWH.DETALLE_CLIENTES
    WHERE
        CAMP_PROM_ID IN (SELECT DISTINCT CAMP_PROM_ID FROM PROMOCIONES_FOCO_NOABANDONO)
    GROUP BY
        ALL
        
)
,
TICKETS_TOTAL_NOABANDONO AS (

    SELECT
        DISTINCT
        TIEM_DIA_ID,
        VNTA_COD_DESCUENTO,
        TICKET,
        CAMP_PROM_ID,
        CAMP_PROM_NOMBRE,
        CAMP_PROM_ESPECIFICACION,
        CAMP_PROM_FINI,
        CAMP_PROM_FFIN,
        CAMP_PROM_UNNG,
        CAMP_PROM_CANAL,
        B.VNTA_CODIGO_PROMOCION
    FROM
        MSTRDB.DWH.FT_VENTAS_DESCUENTOS_LINEAS A
         INNER JOIN PROMOCIONES_FOCO_NOABANDONO B ON (
                A.VNTA_COD_DESCUENTO::VARCHAR = B.VNTA_CODIGO_PROMOCION 
                OR A.VNTA_CODIGO_PROMOCION::VARCHAR = B.VNTA_CODIGO_PROMOCION
                OR A.VNTA_CODIGO::VARCHAR = B.VNTA_CODIGO_PROMOCION
                OR A.VNTA_COD_DESCUENTO::VARCHAR = B.GEO_PROMOTION AND B.GEO_PROMOTION IS NOT NULL
                OR A.VNTA_CODIGO_PROMOCION::VARCHAR = B.GEO_PROMOTION AND B.GEO_PROMOTION IS NOT NULL
                OR A.VNTA_CODIGO::VARCHAR = B.GEO_PROMOTION AND B.GEO_PROMOTION IS NOT NULL
            ) AND A.TIEM_DIA_ID BETWEEN B.CAMP_PROM_FINI AND B.CAMP_PROM_FFIN
    WHERE
        YEAR(TIEM_DIA_ID) >= YEAR(CURRENT_DATE) - 1

) 
,
ACCIONES_FOCO_GENERAL AS (
    SELECT
        'TATA' AS UNIDAD_NEGOCIO,
        'ACCIONES FOCO' AS ACCION,
        'REACTIVACION CLIENTES' AS OBJETIVO,
        YEAR(FV.TIEM_DIA_ID) ANIO,
        MONTH(FV.TIEM_DIA_ID) AS MES,
        COUNT(DISTINCT(FV.TICKET)) AS TICKETS,
        ROUND(SUM(FV.VNTA_IMPORTE_SIN_IVA)) AS VTA_PROMO,
        ROUND(SUM(FV.VNTA_IMPORTE_SIN_IVA - (FV.VNTA_UNIDADES * FV.VNTA_COSTO_PROM_POND))) AS GB1_PROMO,
        ROUND(GB1_PROMO / VTA_PROMO, 2) AS MARGEN_PROMO,
        COUNT(DISTINCT(FFM.SOCI_SOCI_ID)) AS SOCIOS_CON_PROMO,
        IMPACTADOS,
        ROUND((SOCIOS_CON_PROMO / IMPACTADOS) * 100, 2) AS REDENCION
    FROM
        MSTRDB.DWH.FT_VENTAS AS FV
        INNER JOIN MSTRDB.DWH.LU_ARTC_ARTICULO AS LAA ON FV.ARTC_ARTC_ID = LAA.ARTC_ARTC_ID
        LEFT JOIN MSTRDB.DWH.FT_VENTAS_RESUMEN_DESCUENTOS AS VRD ON FV.TICKET = VRD.TICKET AND FV.ARTC_ARTC_ID = VRD.ARTC_ARTC_ID AND VRD.VNTA_COD_DESCUENTO IN (SELECT DISTINCT VNTA_CODIGO_PROMOCION FROM PROMOCIONES_FOCO_NOABANDONO)
        INNER JOIN MSTRDB.DWH.FT_FDLN_MOVIMIENTOS AS FFM ON FV.TICKET = FFM.TICKET AND FV.TIEM_DIA_ID = FFM.TIEM_DIA_ID
        INNER JOIN PROMOCIONES_FOCO_NOABANDONO AS PFN ON VRD.VNTA_COD_DESCUENTO = PFN.VNTA_CODIGO_PROMOCION
        LEFT JOIN IMPACTADOS_NO_ABANDONO AS NA ON NA.ANIO = YEAR(FV.TIEM_DIA_ID) AND NA.MES = MONTH(FV.TIEM_DIA_ID)
    WHERE
        YEAR(FV.TIEM_DIA_ID) >= YEAR(CURRENT_DATE) - 1
        AND FFM.FDLN_MOVT_TIPO = 'RP'
        AND FV.TICKET IN (SELECT DISTINCT TICKET FROM TICKETS_TOTAL_NOABANDONO)
        AND VRD.VNTA_COD_DESCUENTO IS NOT NULL
    GROUP BY
        ALL
ORDER BY
    1 DESC,
    2,
    3
) 
,
CUPONES_SEGMENTADOS AS (

    SELECT
        CAMP_PROM_ID,
        COALESCE(PAZOS_CODIGO_PROMO, VNTA_CODIGO_PROMOCION) AS VNTA_CODIGO_PROMOCION,
        GEO_PROMOTION,
        CAMP_PROM_FINI,
        CAMP_PROM_FFIN,
        CAMP_PROM_UNNG,
        CAMP_PROM_TIPO,
        CAMP_PROM_NOMBRE,
        CAMP_PROM_ESPECIFICACION,
        CAMP_PROM_OBJETIVO,
        CAMP_PROM_APLICACION,
        CAMP_PROM_CANAL
    FROM
        SANDBOX_PLUS.DWH.DETALLE_PROMO AS A
        LEFT JOIN MSTRDB.DWH.LU_PROMO_RPM AS L on L.RPM_CODIGO_PROMO = A.VNTA_CODIGO_PROMOCION
    WHERE
        CAMP_PROM_OBJETIVO <> 'Informativo'
        AND YEAR(CAMP_PROM_FINI) >= YEAR(CURRENT_DATE) - 1
        AND (CAMP_PROM_NOMBRE ILIKE '%SEGMENTADO%')
    ORDER BY
        CAMP_PROM_ID DESC

) 
,
IMPACTADOS_SEGMENTADOS AS (

    SELECT
        YEAR(FECHA_CARGA) AS ANIO,
        MONTH(FECHA_CARGA) AS MES,
        COUNT(DISTINCT(SOCI_SOCI_ID)) AS IMPACTADOS
    FROM
        SANDBOX_PLUS.DWH.DETALLE_CLIENTES
    WHERE
        CAMP_PROM_ID IN (SELECT DISTINCT CAMP_PROM_ID FROM CUPONES_SEGMENTADOS)
    GROUP BY
        ALL
        
)
,
TICKETS_SEGMENTADOS AS (

    SELECT
        DISTINCT
        A.TIEM_DIA_ID,
        SOCI_SOCI_ID,
        A.GEOG_LOCL_ID,
        A.VNTA_NRO_TICKET,
        A.VNTA_NRO_CAJA,
        A.VNTA_COD_DESCUENTO,
        A.TICKET,
        CAMP_PROM_ID,
        CAMP_PROM_NOMBRE,
        CAMP_PROM_ESPECIFICACION,
        CAMP_PROM_FINI,
        CAMP_PROM_FFIN,
        CAMP_PROM_UNNG,
        CAMP_PROM_CANAL,
        B.VNTA_CODIGO_PROMOCION
    FROM
        MSTRDB.DWH.FT_VENTAS_DESCUENTOS_LINEAS A
         INNER JOIN CUPONES_SEGMENTADOS B ON (
                A.VNTA_COD_DESCUENTO::VARCHAR = B.VNTA_CODIGO_PROMOCION 
                OR A.VNTA_CODIGO_PROMOCION::VARCHAR = B.VNTA_CODIGO_PROMOCION
                OR A.VNTA_CODIGO::VARCHAR = B.VNTA_CODIGO_PROMOCION
                OR A.VNTA_COD_DESCUENTO::VARCHAR = B.GEO_PROMOTION AND B.GEO_PROMOTION IS NOT NULL
                OR A.VNTA_CODIGO_PROMOCION::VARCHAR = B.GEO_PROMOTION AND B.GEO_PROMOTION IS NOT NULL
                OR A.VNTA_CODIGO::VARCHAR = B.GEO_PROMOTION AND B.GEO_PROMOTION IS NOT NULL
            ) AND A.TIEM_DIA_ID BETWEEN B.CAMP_PROM_FINI AND B.CAMP_PROM_FFIN
        INNER JOIN MSTRDB.DWH.FT_FDLN_MOVIMIENTOS AS FFM
            ON A.GEOG_LOCL_ID = FFM.GEOG_LOCL_ID
            AND A.VNTA_NRO_TICKET = FFM.VNTA_NRO_TICKET
            AND A.VNTA_NRO_CAJA = FFM.VNTA_NRO_CAJA
            AND A.TIEM_DIA_ID = FFM.TIEM_DIA_ID
            AND FFM.FDLN_MOVT_TIPO = 'RP'
    WHERE
        YEAR(A.TIEM_DIA_ID) >= 2025

) --SELECT * FROM TICKETS_SEGMENTADOS ORDER BY SOCI_SOCI_ID, TICKET;
,
VTA_GENERADA_CUPONES AS (

    SELECT
        FFM.SOCI_SOCI_ID,
        DATE_TRUNC(MONTH, FFM.TIEM_DIA_ID) AS MES,
        ROUND(SUM(A.VNTA_IMPORTE_SIN_IVA)) AS VTA_SIN_IVA_CUPONES,
        ROUND(SUM(A.VNTA_IMPORTE_SIN_IVA - (A.VNTA_UNIDADES * A.VNTA_COSTO_PROM_POND))) AS GB1_CUPONES,
        COUNT(DISTINCT(A.TICKET)) AS TICKETS_CUP,
        ROUND((VTA_SIN_IVA_CUPONES / TICKETS_CUP)) AS TICK_PROM_CUP,
        ROUND((GB1_CUPONES / TICKETS_CUP)) AS GB1_PROM_CUP
    FROM
        MSTRDB.DWH.FT_VENTAS AS A
        INNER JOIN MSTRDB.DWH.FT_FDLN_MOVIMIENTOS AS FFM
            ON A.GEOG_LOCL_ID = FFM.GEOG_LOCL_ID
            AND A.VNTA_NRO_TICKET = FFM.VNTA_NRO_TICKET
            AND A.VNTA_NRO_CAJA = FFM.VNTA_NRO_CAJA
            AND A.TIEM_DIA_ID = FFM.TIEM_DIA_ID
            AND FFM.FDLN_MOVT_TIPO = 'RP'
        INNER JOIN TICKETS_SEGMENTADOS AS T
            ON A.GEOG_LOCL_ID = T.GEOG_LOCL_ID
            AND A.VNTA_NRO_TICKET = T.VNTA_NRO_TICKET
            AND A.VNTA_NRO_CAJA = T.VNTA_NRO_CAJA
            AND A.TIEM_DIA_ID = T.TIEM_DIA_ID
        GROUP BY
            ALL
        ORDER BY
            1,
            2,
            3
            
) --SELECT * FROM VTA_GENERADA_CUPONES;
,
GENERAL_CUP AS (

    SELECT
        YEAR(TIEM_DIA_ID) AS ANIO,
        MONTH(TIEM_DIA_ID) AS MES,
        COUNT(DISTINCT(TICKET)) AS TICKETS
    FROM
        TICKETS_SEGMENTADOS
    GROUP BY    
        ALL

)
,
CONSUMO_CLIE AS (

    SELECT
        FFM.SOCI_SOCI_ID,
        DATE_TRUNC(MONTH, A.TIEM_DIA_ID) AS MES,
        SUM(A.VNTA_IMPORTE_SIN_IVA) AS CONSUMO_PRE,
        ROUND(SUM(A.VNTA_IMPORTE_SIN_IVA - (A.VNTA_UNIDADES * A.VNTA_COSTO_PROM_POND))) AS GB1,
        COUNT(DISTINCT(A.TICKET)) AS TICKETS_PRE,
        ROUND(CONSUMO_PRE / TICKETS_PRE) AS TICK_PROM_PRE,
        ROUND((GB1 / TICKETS_PRE)) AS GB1_PROM_PRE
    FROM
        MSTRDB.DWH.FT_FDLN_MOVIMIENTOS AS FFM
        INNER JOIN MSTRDB.DWH.LU_GEOG_LOCAL AS LGL ON FFM.GEOG_LOCL_ID = LGL.GEOG_LOCL_ID AND LGL.GEOG_UNNG_ID = 2
        INNER JOIN MSTRDB.DWH.FT_VENTAS AS A
            ON A.GEOG_LOCL_ID = FFM.GEOG_LOCL_ID
            AND A.VNTA_NRO_TICKET = FFM.VNTA_NRO_TICKET
            AND A.VNTA_NRO_CAJA = FFM.VNTA_NRO_CAJA
            AND A.TIEM_DIA_ID = FFM.TIEM_DIA_ID
            AND FFM.FDLN_MOVT_TIPO = 'RP'
    WHERE
        YEAR(A.TIEM_DIA_ID) >= YEAR(CURRENT_DATE) - 1
        AND FFM.SOCI_SOCI_ID IN (SELECT DISTINCT SOCI_SOCI_ID FROM VTA_GENERADA_CUPONES)
        AND (A.GEOG_LOCL_ID, A.VNTA_NRO_TICKET, A.VNTA_NRO_CAJA, A.TIEM_DIA_ID) NOT IN (SELECT DISTINCT GEOG_LOCL_ID, VNTA_NRO_TICKET, VNTA_NRO_CAJA, TIEM_DIA_ID FROM TICKETS_SEGMENTADOS)
        AND MONTH(A.TIEM_DIA_ID) NOT IN (3, 12)
    GROUP BY
        ALL
    ORDER BY
        1, 2 DESC

) --SELECT * FROM CONSUMO_CLIE;
,
INC AS (

    SELECT
        V.SOCI_SOCI_ID,
        V.MES,
        VTA_SIN_IVA_CUPONES,
        GB1_CUPONES,
        TICKETS_CUP,
        TICK_PROM_CUP,
        GB1_PROM_CUP,
        C.CONSUMO_PRE,
        C.GB1,
        C.TICKETS_PRE,
        C.TICK_PROM_PRE,
        C.GB1_PROM_PRE,
        ROW_NUMBER() OVER (PARTITION BY V.SOCI_SOCI_ID, V.MES ORDER BY C.MES DESC) AS R
    FROM
        VTA_GENERADA_CUPONES AS V
        LEFT JOIN CONSUMO_CLIE AS C ON V.SOCI_SOCI_ID = C.SOCI_SOCI_ID
    WHERE
        C.MES < V.MES
    QUALIFY
        R <= 3
    ORDER BY
        V.SOCI_SOCI_ID,
        C.MES DESC
    
) --SELECT * FROM INC;
,
INCREMENTAL AS (
    SELECT
        SOCI_SOCI_ID,
        MES,
        MAX(TICK_PROM_CUP)        AS TICK_PROM_CUPONES,
        MAX(GB1_PROM_CUP)         AS GB1_CUPONES,
        MAX(TICKETS_CUP)          AS TICKETS_CUPONES,
        ROUND(AVG(TICK_PROM_PRE)) AS TICK_PROM_PRE,
        ROUND(AVG(GB1_PROM_PRE))  AS GB1_PROM_PRE
    FROM INC
    GROUP BY SOCI_SOCI_ID, MES
),

INCREMENTAL_FINAL AS (
    SELECT
        *,
        TICK_PROM_CUPONES - TICK_PROM_PRE AS VTA_INCREMENTAL,
        GB1_CUPONES - GB1_PROM_PRE        AS GB1_INCREMENTAL
    FROM INCREMENTAL

) --SELECT * FROM INCREMENTAL_FINAL ORDER BY 1;
,
ACCIONES_SEGMENTADOS  AS (
SELECT
    'TATA' AS UNIDAD_NEGOCIO,
    'SEGMENTADOS' AS ACCION,
    'CLIENTES ACTUALES' AS OBJETIVO,
    YEAR(I.MES) AS ANIO,
    MONTH(I.MES) AS MES,
    G.TICKETS,
    SUM(VTA_INCREMENTAL) AS VTA_PROMO,
    SUM(GB1_INCREMENTAL) AS GB1_PROMO,
    ROUND(GB1_PROMO / VTA_PROMO, 2) AS MARGEN,
    COUNT(DISTINCT(SOCI_SOCI_ID)) AS SOCIOS_CON_PROMO,
    IMPACTADOS,
    ROUND((SOCIOS_CON_PROMO / IMPACTADOS) * 100, 2) AS REDENCION
FROM
    INCREMENTAL_FINAL AS I
    LEFT JOIN IMPACTADOS_SEGMENTADOS AS S ON YEAR(I.MES) = S.ANIO AND MONTH(I.MES) = S.MES
    LEFT JOIN GENERAL_CUP AS G ON YEAR(I.MES) = G.ANIO AND MONTH(I.MES) = G.MES 
GROUP BY
    ALL
)
,

------------------------------------------- CUMPLEAÑOS --------------------------------------------------
-- 1. Clientes que usaron descuento de cumpleaños desde 2026 en adelante
CUMPLE AS (
    SELECT DISTINCT
        m.SOCI_SOCI_ID,                          -- ajustar nombre real del campo cliente
        v.TIEM_DIA_ID                          AS FECHA_CUMPLE_USO,
        v.TICKET
    FROM 
        MSTRDB.DWH.FT_VENTAS_DESCUENTOS_LINEAS v
        INNER JOIN MSTRDB.DWH.FT_FDLN_MOVIMIENTOS m ON v.vnta_nro_ticket = m.vnta_nro_ticket AND v.vnta_nro_caja = m.vnta_nro_caja and v.geog_locl_id = m.geog_locl_id and v.tiem_dia_id = m.tiem_dia_id AND m.fdln_movt_tipo = 'RP'
    WHERE 
        v.TIEM_DIA_ID >= '2026-01-01'
        AND (v.VNTA_COD_DESCUENTO IN (3387 , 5000000006) OR v.VNTA_CODIGO_PROMOCION IN (3387 , 5000000006))

) 
,
IMPACTADOS_CUMPLE AS (

    SELECT
        YEAR(FECHA_CARGA) AS ANIO,
        MONTH(FECHA_CARGA) AS MES,
        COUNT(DISTINCT(SOCI_SOCI_ID)) AS IMPACTADOS
    FROM
        SANDBOX_PLUS.DWH.DETALLE_CLIENTES
    WHERE
        CAMP_PROM_ID = 19
    GROUP BY
        ALL

)
,
-- ============================================================
-- 2. Calendario de meses válidos entre 2025-01-01 y hoy
--    Excluye marzo (3) y diciembre (12)
-- ============================================================
calendario_meses AS (
    SELECT MES
    FROM (
        SELECT 
            DATE_TRUNC('month', DATEADD('month', SEQ4(), '2025-01-01')) AS MES
        FROM TABLE(GENERATOR(ROWCOUNT => 36))
    )
    WHERE MONTH(MES) NOT IN (3, 12)
    ORDER BY
        1 DESC

)
,

-- ============================================================
-- 3. Cruzar cada cliente x cada mes válido previo al cupón
--    y rankear los 3 más recientes
-- ============================================================
meses_pre_validos AS (
    SELECT
        b.SOCI_SOCI_ID,
        b.FECHA_CUMPLE_USO,
        c.MES,
        ROW_NUMBER() OVER (
            PARTITION BY b.SOCI_SOCI_ID, b.FECHA_CUMPLE_USO
            ORDER BY c.MES DESC
        )                   AS RN
    FROM CUMPLE b
    JOIN calendario_meses c
        ON  c.MES >= '2025-01-01'
        AND c.MES <  DATE_TRUNC('month', b.FECHA_CUMPLE_USO)
    QUALIFY
        RN <= 3
    ORDER BY
        1,
        3 DESC

)
,

-- ============================================================
-- 4. Consumo real por cliente-mes (puede no existir → 0)
-- ============================================================
consumo_mensual AS (
    SELECT
        m.SOCI_SOCI_ID,
        DATE_TRUNC('month', v.TIEM_DIA_ID)  AS MES,
        SUM(v.VNTA_IMPORTE_SIN_IVA)                  AS MONTO_MES,
        ROUND(SUM(v.VNTA_IMPORTE_SIN_IVA - (v.VNTA_UNIDADES * v.VNTA_COSTO_PROM_POND))) AS GB1_MES
    FROM 
        MSTRDB.DWH.FT_FDLN_MOVIMIENTOS m
        JOIN MSTRDB.DWH.FT_VENTAS v ON v.vnta_nro_ticket = m.vnta_nro_ticket AND v.vnta_nro_caja = m.vnta_nro_caja and v.geog_locl_id = m.geog_locl_id and v.tiem_dia_id = m.tiem_dia_id AND M.FDLN_MOVT_TIPO = 'RP'
        JOIN MSTRDB.DWH.LU_GEOG_LOCAL AS L ON V.GEOG_LOCL_ID = L.GEOG_LOCL_ID AND L.GEOG_UNNG_ID = 2
    WHERE 
        v.TIEM_DIA_ID >= '2025-01-01'
    GROUP BY 1, 2

) 
,

-- ============================================================
-- 5. LEFT JOIN: meses del calendario contra consumo real
--    Si no compró → MONTO_MES = 0. Solo top 3 meses.
-- ============================================================
consumo_pre AS (
    SELECT
        mp.SOCI_SOCI_ID,
        mp.FECHA_CUMPLE_USO,
        COUNT(*)                                        AS MESES_VALIDOS,
        SUM(COALESCE(cm.MONTO_MES, 0))                 AS VTA_TOTAL_PRE,
        SUM(COALESCE(cm.GB1_MES, 0))                 AS GB1_TOTAL_PRE,
        SUM(COALESCE(cm.MONTO_MES, 0)) / COUNT(*)      AS PROMEDIO_MENSUAL_PRE,
        SUM(COALESCE(cm.GB1_MES, 0)) / COUNT(*)      AS GB1_MENSUAL_PRE,
    FROM meses_pre_validos mp
    LEFT JOIN consumo_mensual cm
        ON  cm.SOCI_SOCI_ID = mp.SOCI_SOCI_ID
        AND cm.MES        = mp.MES
    WHERE 
        mp.RN <= 3
    GROUP BY 
        1, 2

) 
,

-- ============================================================
-- 6. Consumo POST: 30 días corridos desde la fecha del cupón
-- ============================================================
consumo_post AS (
    SELECT
        b.SOCI_SOCI_ID,
        b.FECHA_CUMPLE_USO,
        SUM(v.VNTA_IMPORTE_SIN_IVA)  AS VTA_TOTAL_POST,
        ROUND(SUM(v.VNTA_IMPORTE_SIN_IVA - (v.VNTA_UNIDADES * v.VNTA_COSTO_PROM_POND))) AS GB1_TOTAL_POST,
        DATEADD('day', 30, b.FECHA_CUMPLE_USO) AS FECHA_FIN_ACUMULO
    FROM 
        CUMPLE b
        JOIN MSTRDB.DWH.FT_FDLN_MOVIMIENTOS m ON m.SOCI_SOCI_ID = b.SOCI_SOCI_ID
        JOIN MSTRDB.DWH.FT_VENTAS v           ON v.vnta_nro_ticket = m.vnta_nro_ticket AND v.vnta_nro_caja = m.vnta_nro_caja and v.geog_locl_id = m.geog_locl_id and v.tiem_dia_id = m.tiem_dia_id AND M.FDLN_MOVT_TIPO = 'RP'
        JOIN MSTRDB.DWH.LU_GEOG_LOCAL AS L ON V.GEOG_LOCL_ID = L.GEOG_LOCL_ID AND L.GEOG_UNNG_ID = 2
    WHERE
        v.TIEM_DIA_ID >= b.FECHA_CUMPLE_USO
        AND v.TIEM_DIA_ID <  DATEADD('day', 30, b.FECHA_CUMPLE_USO)
    GROUP BY 1, 2

) 

-- ============================================================
-- 7. Join final + incremental
-- ============================================================
,
FINAL AS (
    SELECT
        p.SOCI_SOCI_ID,
        p.FECHA_CUMPLE_USO,
        p.MESES_VALIDOS,
        VTA_TOTAL_PRE,
        GB1_TOTAL_PRE,
        PROMEDIO_MENSUAL_PRE,
        GB1_MENSUAL_PRE,
        FECHA_FIN_ACUMULO,
        COALESCE(po.VTA_TOTAL_POST, 0) AS VTA_TOTAL_POST_30_DIAS,
        COALESCE(po.GB1_TOTAL_POST, 0) AS GB1_TOTAL_POST_30_DIAS,
        COALESCE(VTA_TOTAL_POST_30_DIAS, 0) - p.PROMEDIO_MENSUAL_PRE  AS INCREMENTAL_VTA,
        COALESCE(GB1_TOTAL_POST_30_DIAS, 0) - p.GB1_MENSUAL_PRE  AS INCREMENTAL_GB1,
    FROM 
        consumo_pre p
        LEFT JOIN consumo_post po ON  po.SOCI_SOCI_ID = p.SOCI_SOCI_ID AND po.FECHA_CUMPLE_USO = p.FECHA_CUMPLE_USO
    WHERE
        FECHA_FIN_ACUMULO <= CURRENT_DATE - 1 
    ORDER BY
        p.FECHA_CUMPLE_USO DESC,
        p.SOCI_SOCI_ID

)
,
ACCIONES_CUMPLE AS (
    SELECT
        'TATA' AS UNIDAD_NEGOCIO,
        'CUMPLE' AS ACCION,
        'CLIENTES ACTUALES' AS OBJETIVO,
        YEAR(FECHA_CUMPLE_USO) ANIO,
        MONTH(FECHA_CUMPLE_USO) AS MES,
        COUNT(DISTINCT(SOCI_SOCI_ID)) AS TICKETS,
        ROUND(SUM(INCREMENTAL_VTA)) AS VTA_PROMO,
        ROUND(SUM(INCREMENTAL_GB1)) AS GB1_PROMO,
        ROUND(GB1_PROMO / VTA_PROMO, 2) AS MARGEN_PROMO,
        COUNT(DISTINCT(SOCI_SOCI_ID)) AS SOCIOS_CON_PROMO,
        IMPACTADOS,
        ROUND((SOCIOS_CON_PROMO / IMPACTADOS) * 100, 2) AS REDENCION
    FROM 
        FINAL
        LEFT JOIN IMPACTADOS_CUMPLE AS IC ON YEAR(FECHA_CUMPLE_USO) = IC.ANIO AND MONTH(FECHA_CUMPLE_USO) = IC.MES
    GROUP BY ALL
    ORDER BY 3, 4
    
) 

------------------------------------------- CUOTA --------------------------------------------------
,
CUPONES_CUOTA AS (

    SELECT
        CAMP_PROM_ID,
        COALESCE(PAZOS_CODIGO_PROMO, VNTA_CODIGO_PROMOCION) AS VNTA_CODIGO_PROMOCION,
        GEO_PROMOTION,
        CAMP_PROM_FINI,
        CAMP_PROM_FFIN,
        CAMP_PROM_UNNG,
        CAMP_PROM_TIPO,
        CAMP_PROM_NOMBRE,
        CAMP_PROM_ESPECIFICACION,
        CAMP_PROM_OBJETIVO,
        CAMP_PROM_APLICACION,
        CAMP_PROM_CANAL
    FROM
        SANDBOX_PLUS.DWH.DETALLE_PROMO AS A
        LEFT JOIN MSTRDB.DWH.LU_PROMO_RPM AS L on L.RPM_CODIGO_PROMO = A.VNTA_CODIGO_PROMOCION
    WHERE
        CAMP_PROM_OBJETIVO <> 'Informativo'
        AND (CAMP_PROM_NOMBRE ILIKE '%CUOTA%')
    ORDER BY
        CAMP_PROM_ID DESC

) 
,
IMPACTADOS_CUOTA AS (

    SELECT
        YEAR(FECHA_CARGA) AS ANIO,
        MONTH(FECHA_CARGA) AS MES,
        COUNT(DISTINCT(SOCI_SOCI_ID)) AS IMPACTADOS
    FROM
        SANDBOX_PLUS.DWH.DETALLE_CLIENTES
    WHERE
        CAMP_PROM_ID IN (SELECT DISTINCT CAMP_PROM_ID FROM CUPONES_CUOTA)
    GROUP BY
        ALL

)
,
TICKETS_CUOTA AS (

    SELECT
        DISTINCT
        TIEM_DIA_ID,
        GEOG_LOCL_ID,
        VNTA_NRO_TICKET,
        VNTA_NRO_CAJA,
        VNTA_COD_DESCUENTO,
        TICKET,
        CAMP_PROM_ID,
        CAMP_PROM_NOMBRE,
        CAMP_PROM_ESPECIFICACION,
        CAMP_PROM_FINI,
        CAMP_PROM_FFIN,
        CAMP_PROM_UNNG,
        CAMP_PROM_CANAL,
        B.VNTA_CODIGO_PROMOCION
    FROM
        MSTRDB.DWH.FT_VENTAS_DESCUENTOS_LINEAS A
         INNER JOIN CUPONES_CUOTA B ON (
                A.VNTA_COD_DESCUENTO::VARCHAR = B.VNTA_CODIGO_PROMOCION 
                OR A.VNTA_CODIGO_PROMOCION::VARCHAR = B.VNTA_CODIGO_PROMOCION
                OR A.VNTA_CODIGO::VARCHAR = B.VNTA_CODIGO_PROMOCION
                OR A.VNTA_COD_DESCUENTO::VARCHAR = B.GEO_PROMOTION AND B.GEO_PROMOTION IS NOT NULL
                OR A.VNTA_CODIGO_PROMOCION::VARCHAR = B.GEO_PROMOTION AND B.GEO_PROMOTION IS NOT NULL
                OR A.VNTA_CODIGO::VARCHAR = B.GEO_PROMOTION AND B.GEO_PROMOTION IS NOT NULL
            ) AND A.TIEM_DIA_ID BETWEEN B.CAMP_PROM_FINI AND B.CAMP_PROM_FFIN
    WHERE
        YEAR(TIEM_DIA_ID) >= YEAR(CURRENT_DATE) 

)
,
ACCIONES_CUOTA AS (
    SELECT
        'TATA' AS UNIDAD_NEGOCIO,
        'CUOTA' AS ACCION,
        'CLIENTES ACTUALES' AS OBJETIVO,
        YEAR(FV.TIEM_DIA_ID) ANIO,
        MONTH(FV.TIEM_DIA_ID) AS MES,
        COUNT(DISTINCT(FV.TICKET)) AS TICKETS,
        ROUND(SUM(FV.VNTA_IMPORTE_SIN_IVA)) AS VTA_PROMO,
        ROUND(SUM(FV.VNTA_IMPORTE_SIN_IVA - (FV.VNTA_UNIDADES * FV.VNTA_COSTO_PROM_POND))) AS GB1_PROMO,
        ROUND(GB1_PROMO / VTA_PROMO, 2) AS MARGEN_PROMO,
        COUNT(DISTINCT(FFM.SOCI_SOCI_ID)) AS SOCIOS_CON_PROMO,
        IMPACTADOS,
        ROUND((SOCIOS_CON_PROMO / IMPACTADOS) * 100, 2) AS REDENCION
    FROM
        MSTRDB.DWH.FT_VENTAS AS FV
        INNER JOIN TICKETS_CUOTA AS TT
            ON FV.TIEM_DIA_ID = TT.TIEM_DIA_ID 
            AND FV.VNTA_NRO_TICKET = TT.VNTA_NRO_TICKET 
            AND FV.GEOG_LOCL_ID = TT.GEOG_LOCL_ID
            AND FV.VNTA_NRO_CAJA = TT.VNTA_NRO_CAJA
        INNER JOIN MSTRDB.DWH.LU_ARTC_ARTICULO AS LAA ON FV.ARTC_ARTC_ID = LAA.ARTC_ARTC_ID
        INNER JOIN MSTRDB.DWH.FT_FDLN_MOVIMIENTOS AS FFM 
            ON FV.TIEM_DIA_ID = FFM.TIEM_DIA_ID 
            AND FV.VNTA_NRO_TICKET = FFM.VNTA_NRO_TICKET
            AND FV.GEOG_LOCL_ID = FFM.GEOG_LOCL_ID 
            AND FV.VNTA_NRO_CAJA = FFM.VNTA_NRO_CAJA 
        LEFT JOIN IMPACTADOS_CUOTA AS IM ON YEAR(FV.TIEM_DIA_ID) = IM.ANIO AND MONTH(FV.TIEM_DIA_ID) = IM.MES
    WHERE
        YEAR(FV.TIEM_DIA_ID) >= YEAR(CURRENT_DATE)
        AND FFM.FDLN_MOVT_TIPO = 'RP'
    GROUP BY
        ALL
ORDER BY
    1 DESC,
    2,
    3
) 
,
------------------------------------------- BAS USOS ------------------------------------------------------

CUPONES_BAS AS (

    SELECT
        CAMP_PROM_ID,
        COALESCE(PAZOS_CODIGO_PROMO, VNTA_CODIGO_PROMOCION) AS VNTA_CODIGO_PROMOCION,
        GEO_PROMOTION,
        CAMP_PROM_FINI,
        CAMP_PROM_FFIN,
        CAMP_PROM_UNNG,
        CAMP_PROM_TIPO,
        CAMP_PROM_NOMBRE,
        CAMP_PROM_ESPECIFICACION,
        CAMP_PROM_OBJETIVO,
        CAMP_PROM_APLICACION,
        CAMP_PROM_CANAL
    FROM
        SANDBOX_PLUS.DWH.DETALLE_PROMO AS A
        LEFT JOIN MSTRDB.DWH.LU_PROMO_RPM AS L on L.RPM_CODIGO_PROMO = A.VNTA_CODIGO_PROMOCION
    WHERE
        CAMP_PROM_OBJETIVO <> 'Informativo'
        AND (CAMP_PROM_NOMBRE ILIKE '%Cupones BAS%')
    ORDER BY
        CAMP_PROM_ID DESC

) --SELECT * FROM CUPONES_BAS;
,
IMPACTADOS_CUPONES_BAS AS (

    SELECT
        YEAR(FECHA_CARGA) AS ANIO,
        MONTH(FECHA_CARGA) AS MES,
        COUNT(DISTINCT(SOCI_SOCI_ID)) AS IMPACTADOS
    FROM
        SANDBOX_PLUS.DWH.DETALLE_CLIENTES
    WHERE
        CAMP_PROM_ID IN (SELECT DISTINCT CAMP_PROM_ID FROM CUPONES_BAS)
    GROUP BY
        ALL

)
,
TICKETS_BAS AS (

    SELECT
        DISTINCT
        TIEM_DIA_ID,
        GEOG_LOCL_ID,
        VNTA_NRO_TICKET,
        VNTA_NRO_CAJA,
        VNTA_COD_DESCUENTO,
        TICKET,
        CAMP_PROM_ID,
        CAMP_PROM_NOMBRE,
        CAMP_PROM_ESPECIFICACION,
        CAMP_PROM_FINI,
        CAMP_PROM_FFIN,
        CAMP_PROM_UNNG,
        CAMP_PROM_CANAL,
        B.VNTA_CODIGO_PROMOCION
    FROM
        MSTRDB.DWH.FT_VENTAS_DESCUENTOS_LINEAS A
         INNER JOIN CUPONES_BAS B ON (
                A.VNTA_COD_DESCUENTO::VARCHAR = B.VNTA_CODIGO_PROMOCION 
                OR A.VNTA_CODIGO_PROMOCION::VARCHAR = B.VNTA_CODIGO_PROMOCION
                OR A.VNTA_CODIGO::VARCHAR = B.VNTA_CODIGO_PROMOCION
                OR A.VNTA_COD_DESCUENTO::VARCHAR = B.GEO_PROMOTION AND B.GEO_PROMOTION IS NOT NULL
                OR A.VNTA_CODIGO_PROMOCION::VARCHAR = B.GEO_PROMOTION AND B.GEO_PROMOTION IS NOT NULL
                OR A.VNTA_CODIGO::VARCHAR = B.GEO_PROMOTION AND B.GEO_PROMOTION IS NOT NULL
            ) AND A.TIEM_DIA_ID BETWEEN B.CAMP_PROM_FINI AND B.CAMP_PROM_FFIN
    WHERE
        YEAR(TIEM_DIA_ID) >= YEAR(CURRENT_DATE) 

) --SELECT * FROM TICKETS_BAS;
,
ACCIONES_BAS AS (
    SELECT
        'BAS' AS UNIDAD_NEGOCIO,
        'CUPONES BAS' AS ACCION,
        'REACTIVACION CLIENTES' AS OBJETIVO,
        YEAR(FV.TIEM_DIA_ID) ANIO,
        MONTH(FV.TIEM_DIA_ID) AS MES,
        COUNT(DISTINCT(FV.TICKET)) AS TICKETS,
        ROUND(SUM(FV.VNTA_IMPORTE_SIN_IVA)) AS VTA_PROMO,
        ROUND(SUM(FV.VNTA_IMPORTE_SIN_IVA - (FV.VNTA_UNIDADES * FV.VNTA_COSTO_PROM_POND))) AS GB1_PROMO,
        ROUND(GB1_PROMO / VTA_PROMO, 2) AS MARGEN_PROMO,
        COUNT(DISTINCT(FFM.SOCI_SOCI_ID)) AS SOCIOS_CON_PROMO,
        IMPACTADOS,
        ROUND((SOCIOS_CON_PROMO / IMPACTADOS) * 100, 2) AS REDENCION
    FROM
        MSTRDB.DWH.FT_VENTAS AS FV
        INNER JOIN TICKETS_BAS AS TT
            ON FV.TIEM_DIA_ID = TT.TIEM_DIA_ID 
            AND FV.VNTA_NRO_TICKET = TT.VNTA_NRO_TICKET 
            AND FV.GEOG_LOCL_ID = TT.GEOG_LOCL_ID
            AND FV.VNTA_NRO_CAJA = TT.VNTA_NRO_CAJA
        INNER JOIN MSTRDB.DWH.LU_ARTC_ARTICULO AS LAA ON FV.ARTC_ARTC_ID = LAA.ARTC_ARTC_ID
        INNER JOIN MSTRDB.DWH.FT_FDLN_MOVIMIENTOS AS FFM 
            ON FV.TIEM_DIA_ID = FFM.TIEM_DIA_ID 
            AND FV.VNTA_NRO_TICKET = FFM.VNTA_NRO_TICKET
            AND FV.GEOG_LOCL_ID = FFM.GEOG_LOCL_ID 
            AND FV.VNTA_NRO_CAJA = FFM.VNTA_NRO_CAJA 
        LEFT JOIN IMPACTADOS_CUPONES_BAS AS IM ON YEAR(FV.TIEM_DIA_ID) = IM.ANIO AND MONTH(FV.TIEM_DIA_ID) = IM.MES
    WHERE
        YEAR(FV.TIEM_DIA_ID) >= YEAR(CURRENT_DATE)
        AND FFM.FDLN_MOVT_TIPO = 'RP'
    GROUP BY
        ALL
ORDER BY
    1 DESC,
    2,
    3
) 

------------------------------------------- MARCA PROPIA --------------------------------------------------

,
MARCA_PROPIA AS (

    SELECT
        CAMP_PROM_ID,
        COALESCE(PAZOS_CODIGO_PROMO, VNTA_CODIGO_PROMOCION) AS VNTA_CODIGO_PROMOCION,
        GEO_PROMOTION,
        CAMP_PROM_FINI,
        CAMP_PROM_FFIN,
        CAMP_PROM_UNNG,
        CAMP_PROM_TIPO,
        CAMP_PROM_NOMBRE,
        CAMP_PROM_ESPECIFICACION,
        CAMP_PROM_OBJETIVO,
        CAMP_PROM_APLICACION,
        CAMP_PROM_CANAL
    FROM
        SANDBOX_PLUS.DWH.DETALLE_PROMO AS A
        LEFT JOIN MSTRDB.DWH.LU_PROMO_RPM AS L on L.RPM_CODIGO_PROMO = A.VNTA_CODIGO_PROMOCION
    WHERE
        CAMP_PROM_OBJETIVO <> 'Informativo'
        AND (CAMP_PROM_NOMBRE ILIKE '%MARCA PROPIA%')
    ORDER BY
        CAMP_PROM_ID DESC

) 
,
CODIGOS_MP AS (

    SELECT
        DISTINCT VNTA_CODIGO_PROMOCION AS CODIGO_PROMO
    FROM 
        MARCA_PROPIA 
    WHERE 
        VNTA_CODIGO_PROMOCION IS NOT NULL
    
    UNION ALL 
    
    SELECT 
        DISTINCT GEO_PROMOTION AS CODIGO_PROMO
    FROM 
        MARCA_PROPIA 
    WHERE 
        GEO_PROMOTION IS NOT NULL

)
,
IMPACTADOS_MP AS (

    SELECT
        YEAR(FECHA_CARGA) AS ANIO,
        MONTH(FECHA_CARGA) AS MES,
        COUNT(DISTINCT(SOCI_SOCI_ID)) AS IMPACTADOS
    FROM
        SANDBOX_PLUS.DWH.DETALLE_CLIENTES
    WHERE
        CAMP_PROM_ID IN (SELECT DISTINCT CAMP_PROM_ID FROM MARCA_PROPIA)
    GROUP BY
        ALL

) 
,
TICKETS_MP AS (

    SELECT
        DISTINCT
        TIEM_DIA_ID,
        GEOG_LOCL_ID,
        VNTA_NRO_TICKET,
        VNTA_NRO_CAJA,
        VNTA_COD_DESCUENTO,
        TICKET,
        CAMP_PROM_ID,
        CAMP_PROM_NOMBRE,
        CAMP_PROM_ESPECIFICACION,
        CAMP_PROM_FINI,
        CAMP_PROM_FFIN,
        CAMP_PROM_UNNG,
        CAMP_PROM_CANAL,
        B.VNTA_CODIGO_PROMOCION
    FROM
        MSTRDB.DWH.FT_VENTAS_DESCUENTOS_LINEAS A
         INNER JOIN MARCA_PROPIA B ON (
                A.VNTA_COD_DESCUENTO::VARCHAR = B.VNTA_CODIGO_PROMOCION 
                OR A.VNTA_CODIGO_PROMOCION::VARCHAR = B.VNTA_CODIGO_PROMOCION
                OR A.VNTA_CODIGO::VARCHAR = B.VNTA_CODIGO_PROMOCION
                OR A.VNTA_COD_DESCUENTO::VARCHAR = B.GEO_PROMOTION AND B.GEO_PROMOTION IS NOT NULL
                OR A.VNTA_CODIGO_PROMOCION::VARCHAR = B.GEO_PROMOTION AND B.GEO_PROMOTION IS NOT NULL
                OR A.VNTA_CODIGO::VARCHAR = B.GEO_PROMOTION AND B.GEO_PROMOTION IS NOT NULL
            ) AND A.TIEM_DIA_ID BETWEEN B.CAMP_PROM_FINI AND B.CAMP_PROM_FFIN
    WHERE
        YEAR(TIEM_DIA_ID) >= YEAR(CURRENT_DATE) 

) 
,
ACCIONES_MP AS (
    SELECT
        'TATA' AS UNIDAD_NEGOCIO,
        'MARCA PROPIA' AS ACCION,
        'CLIENTES ACTUALES' AS OBJETIVO,
        YEAR(FV.TIEM_DIA_ID) ANIO,
        MONTH(FV.TIEM_DIA_ID) AS MES,
        COUNT(DISTINCT(FV.TICKET)) AS TICKETS,
        ROUND(SUM(FV.VNTA_IMPORTE_SIN_IVA)) AS VTA_PROMO,
        ROUND(SUM(FV.VNTA_IMPORTE_SIN_IVA - (FV.VNTA_UNIDADES * FV.VNTA_COSTO_PROM_POND))) AS GB1_PROMO,
        ROUND(GB1_PROMO / VTA_PROMO, 2) AS MARGEN_PROMO,
        COUNT(DISTINCT(FFM.SOCI_SOCI_ID)) AS SOCIOS_CON_PROMO,
        IMPACTADOS,
        ROUND((SOCIOS_CON_PROMO / IMPACTADOS) * 100, 2) AS REDENCION
    FROM
        MSTRDB.DWH.FT_VENTAS AS FV
        INNER JOIN TICKETS_MP AS TT
            ON FV.TIEM_DIA_ID = TT.TIEM_DIA_ID 
            AND FV.VNTA_NRO_TICKET = TT.VNTA_NRO_TICKET 
            AND FV.GEOG_LOCL_ID = TT.GEOG_LOCL_ID
            AND FV.VNTA_NRO_CAJA = TT.VNTA_NRO_CAJA
        INNER JOIN MSTRDB.DWH.LU_ARTC_ARTICULO AS LAA ON FV.ARTC_ARTC_ID = LAA.ARTC_ARTC_ID
        LEFT JOIN MSTRDB.DWH.FT_VENTAS_RESUMEN_DESCUENTOS AS VRD 
            ON FV.TIEM_DIA_ID = VRD.TIEM_DIA_ID 
            AND FV.VNTA_NRO_TICKET = VRD.VNTA_NRO_TICKET
            AND FV.GEOG_LOCL_ID = VRD.GEOG_LOCL_ID 
            AND FV.VNTA_NRO_CAJA = VRD.VNTA_NRO_CAJA 
            AND FV.ARTC_ARTC_ID = VRD.ARTC_ARTC_ID 
            AND VRD.VNTA_COD_DESCUENTO IN (SELECT DISTINCT CODIGO_PROMO FROM CODIGOS_MP)
        INNER JOIN MSTRDB.DWH.FT_FDLN_MOVIMIENTOS AS FFM 
            ON FV.TIEM_DIA_ID = FFM.TIEM_DIA_ID 
            AND FV.VNTA_NRO_TICKET = FFM.VNTA_NRO_TICKET
            AND FV.GEOG_LOCL_ID = FFM.GEOG_LOCL_ID 
            AND FV.VNTA_NRO_CAJA = FFM.VNTA_NRO_CAJA 
        
        LEFT JOIN IMPACTADOS_MP AS IM ON YEAR(FV.TIEM_DIA_ID) = IM.ANIO AND MONTH(FV.TIEM_DIA_ID) = IM.MES
    WHERE
        YEAR(FV.TIEM_DIA_ID) >= YEAR(CURRENT_DATE) - 1
        AND FFM.FDLN_MOVT_TIPO = 'RP'
        AND VRD.VNTA_COD_DESCUENTO IS NOT NULL
    GROUP BY
        ALL
ORDER BY
    1 DESC,
    2,
    3

) 

-------------------------------------------------------------------------- CUPONES APP --------------------------------------------------

,
CUPONES_APP AS (

    SELECT
        CAMP_PROM_ID,
        COALESCE(PAZOS_CODIGO_PROMO, VNTA_CODIGO_PROMOCION) AS VNTA_CODIGO_PROMOCION,
        GEO_PROMOTION,
        CAMP_PROM_FINI,
        CAMP_PROM_FFIN,
        CAMP_PROM_UNNG,
        CAMP_PROM_TIPO,
        CAMP_PROM_NOMBRE,
        CAMP_PROM_ESPECIFICACION,
        CAMP_PROM_OBJETIVO,
        CAMP_PROM_APLICACION,
        CAMP_PROM_CANAL
    FROM
        SANDBOX_PLUS.DWH.DETALLE_PROMO AS A
        LEFT JOIN MSTRDB.DWH.LU_PROMO_RPM AS L on L.RPM_CODIGO_PROMO = A.VNTA_CODIGO_PROMOCION
    WHERE
        CAMP_PROM_OBJETIVO <> 'Informativo'
        AND (CAMP_PROM_NOMBRE ILIKE '%Cupones APP')
    ORDER BY
        CAMP_PROM_ID DESC

) 
,
IMPACTADOS_APP AS (

    SELECT
        YEAR(FECHA_CARGA) AS ANIO,
        MONTH(FECHA_CARGA) AS MES,
        COUNT(DISTINCT(SOCI_SOCI_ID)) AS IMPACTADOS
    FROM
        SANDBOX_PLUS.DWH.DETALLE_CLIENTES
    WHERE
        CAMP_PROM_ID IN (SELECT DISTINCT CAMP_PROM_ID FROM CUPONES_APP)
    GROUP BY
        ALL

)
,
TICKETS_APP AS (

    SELECT
        DISTINCT
        TIEM_DIA_ID,
        VNTA_COD_DESCUENTO,
        TICKET,
        CAMP_PROM_ID,
        CAMP_PROM_NOMBRE,
        CAMP_PROM_ESPECIFICACION,
        CAMP_PROM_FINI,
        CAMP_PROM_FFIN,
        CAMP_PROM_UNNG,
        CAMP_PROM_CANAL,
        B.VNTA_CODIGO_PROMOCION
    FROM
        MSTRDB.DWH.FT_VENTAS_DESCUENTOS_LINEAS A
         INNER JOIN CUPONES_APP B ON (
                A.VNTA_COD_DESCUENTO::VARCHAR = B.VNTA_CODIGO_PROMOCION 
                OR A.VNTA_CODIGO_PROMOCION::VARCHAR = B.VNTA_CODIGO_PROMOCION
                OR A.VNTA_CODIGO::VARCHAR = B.VNTA_CODIGO_PROMOCION
                OR A.VNTA_COD_DESCUENTO::VARCHAR = B.GEO_PROMOTION AND B.GEO_PROMOTION IS NOT NULL
                OR A.VNTA_CODIGO_PROMOCION::VARCHAR = B.GEO_PROMOTION AND B.GEO_PROMOTION IS NOT NULL
                OR A.VNTA_CODIGO::VARCHAR = B.GEO_PROMOTION AND B.GEO_PROMOTION IS NOT NULL
            ) AND A.TIEM_DIA_ID BETWEEN B.CAMP_PROM_FINI AND B.CAMP_PROM_FFIN
    WHERE
        YEAR(TIEM_DIA_ID) >= YEAR(CURRENT_DATE) 

)
,
ACCIONES_APP AS (
    SELECT
        'TATA' AS UNIDAD_NEGOCIO,
        'APP' AS ACCION,
        'REACTIVACION CLIENTES' AS OBJETIVO,
        YEAR(FV.TIEM_DIA_ID) ANIO,
        MONTH(FV.TIEM_DIA_ID) AS MES,
        COUNT(DISTINCT(FV.TICKET)) AS TICKETS,
        ROUND(SUM(FV.VNTA_IMPORTE_SIN_IVA)) AS VTA_PROMO,
        ROUND(SUM(FV.VNTA_IMPORTE_SIN_IVA - (FV.VNTA_UNIDADES * FV.VNTA_COSTO_PROM_POND))) AS GB1_PROMO,
        ROUND(GB1_PROMO / VTA_PROMO, 2) AS MARGEN_PROMO,
        COUNT(DISTINCT(FFM.SOCI_SOCI_ID)) AS SOCIOS_CON_PROMO,
        IMPACTADOS,
        ROUND((SOCIOS_CON_PROMO / IMPACTADOS) * 100, 2) AS REDENCION
    FROM
        MSTRDB.DWH.FT_VENTAS AS FV
        INNER JOIN MSTRDB.DWH.LU_ARTC_ARTICULO AS LAA ON FV.ARTC_ARTC_ID = LAA.ARTC_ARTC_ID
        INNER JOIN MSTRDB.DWH.FT_FDLN_MOVIMIENTOS AS FFM ON FV.TICKET = FFM.TICKET AND FV.TIEM_DIA_ID = FFM.TIEM_DIA_ID
        LEFT JOIN IMPACTADOS_APP AS IM ON YEAR(FV.TIEM_DIA_ID) = IM.ANIO AND MONTH(FV.TIEM_DIA_ID) = IM.MES
    WHERE
        YEAR(FV.TIEM_DIA_ID) >= YEAR(CURRENT_DATE)
        AND FFM.FDLN_MOVT_TIPO = 'RP'
        AND FV.TICKET IN (SELECT DISTINCT TICKET FROM TICKETS_APP)
    GROUP BY
        ALL
ORDER BY
    1 DESC,
    2,
    3
) 

--------

SELECT
    UNIDAD_NEGOCIO,
    OBJETIVO,
    ACCION,
    ANIO,
    MES,
    TICKETS,
    VTA_PROMO,
    GB1_PROMO,
    SOCIOS_CON_PROMO AS CLIENTES_USO,
    IMPACTADOS,
    REDENCION
FROM
    (
    (SELECT * FROM ACCIONES_SEGMENTADOS)
    UNION ALL
    (SELECT * FROM ACCIONES_FOCO_GENERAL)
    UNION ALL
    (SELECT * FROM ACCION_ABANDONO_TOTAL)
    UNION ALL
    (SELECT * FROM ACCIONES_CUMPLE)
    UNION ALL
    (SELECT * FROM ACCIONES_CUOTA)
    UNION ALL
    (SELECT * FROM ACCIONES_MP)
    UNION ALL
    (SELECT * FROM ACCIONES_APP)
    UNION ALL
    (SELECT * FROM ACCIONES_BAS)
    )
WHERE
    ANIO >= 2025
GROUP BY
    ALL
ORDER BY
    2,
    3,
    1;